name: Test

on:
  push:
    # tags:
    #   - 'Test*'
    #   - 'Release*'

jobs:
  # justEcho1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "schaumer mal"
  # justEchoTest:
  #   if: startsWith(github.ref, 'refs/tags/Test')
  #   needs: [justEcho1]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Just echo Test
  #       run: echo "Hallo Test ${{ github.ref }}"
  # justEchoRelease:
  #   if: startsWith(github.ref, 'refs/tags/Release') 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Just echo Release
  #       run: echo "Hallo Test ${{ github.ref }}"
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: MYVARIABLE
        id: MYVARIABLE
        run: | 
          echo "::set-output name=var1::$(sed -n -e '/$string1/ s/.*\= *//p' ./test.test)"
          echo "::set-output name=var2::$(sed -n -e '/$string2/ s/.*\= *//p' ./test.test)"
      - name: Output
        run: echo "${{ steps.MYVARIABLE.outputs.var1 }} - ${{ steps.MYVARIABLE.outputs.var1 }}"
      - name: zz
        run: |
          echo 'TEST_TEST<<EOF' >> $GITHUB_ENV
          cat ./test.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: zz1
        run: |
          echo '${{ fromJson(env.TEST_TEST).string1 }} - ${{ fromJson(env.TEST_TEST).string2 }}'
