name: Test

on:
  push:
    tags:
      - 'Test*'
      - 'Release*'

jobs:
  echoTest:
    if: startsWith(${{ github.ref }}, 'refs/tags/Test') 
    runs-on: ubuntu-latest
    steps:
      - name: Just echo Test
        run: echo "Hallo Test ${{ github.ref }}"
  echoRelease:
    if: startsWith(${{ github.ref }}, 'refs/tags/Release') 
    runs-on: ubuntu-latest
    steps:
      - name: Just echo Release
        run: echo "Hallo Release ${{ github.ref }}"
