name: Test

on:
  push:
    # tags:
    #   - 'Test*'
    #   - 'Release*'

jobs:
  # justEcho1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "schaumer mal"
  # justEchoTest:
  #   if: startsWith(github.ref, 'refs/tags/Test')
  #   needs: [justEcho1]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Just echo Test
  #       run: echo "Hallo Test ${{ github.ref }}"
  # justEchoRelease:
  #   if: startsWith(github.ref, 'refs/tags/Release') 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Just echo Release
  #       run: echo "Hallo Test ${{ github.ref }}"
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: MYVARIABLE
        id: MYVARIABLE
        run: echo "::set-output name=MYVARIABLE::$(sed -n -e '/$string1/ s/.*\= *//p' ./test.test)"
      - name: MYVARIABLE1
        id: MYVARIABLE1
        run: echo "::set-output name=MYVARIABLE::$(sed -n -e '/$string2/ s/.*\= *//p' ./test.test)"
      - name: Output
        run: echo "${{ steps.MYVARIABLE.outputs.MYVARIABLE }} - ${{ steps.MYVARIABLE1.outputs.MYVARIABLE }}"
      - name: Tt
        id: tt
        run: |
          content=`cat ./test.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=TEST::$content"
      # - name: aa
      #   run: | 
      #     echo "${{ steps.tt.outputs.TEST }}" | jq "{string1: .[].string1}"
      - name: zz
        run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: zz1
        run: |
          echo '${{ fromJson(env.PACKAGE_JSON).version }}'
