name: Test

on:
  push:
    # tags:
    #   - 'Test*'
    #   - 'Release*'

jobs:
  # justEcho1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "schaumer mal"
  # justEchoTest:
  #   if: startsWith(github.ref, 'refs/tags/Test')
  #   needs: [justEcho1]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Just echo Test
  #       run: echo "Hallo Test ${{ github.ref }}"
  # justEchoRelease:
  #   if: startsWith(github.ref, 'refs/tags/Release') 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Just echo Release
  #       run: echo "Hallo Test ${{ github.ref }}"
  package:
    # if: startsWith(github.ref, 'refs/tags/Release') 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Echo ls
        run: ls -la && pwd
      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: package.json
      - name: File contents
        run: echo "${steps.read_file.outputs}"
