name: Test

on:
  push:
    # tags:
    #   - 'Test*'
    #   - 'Release*'

jobs:
  # justEcho1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "schaumer mal"
  # justEchoTest:
  #   if: startsWith(github.ref, 'refs/tags/Test')
  #   needs: [justEcho1]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Just echo Test
  #       run: echo "Hallo Test ${{ github.ref }}"
  # justEchoRelease:
  #   if: startsWith(github.ref, 'refs/tags/Release') 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Just echo Release
  #       run: echo "Hallo Test ${{ github.ref }}"
  file_contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: MYVARIABLE
        id: MYVARIABLE
        run: echo "::set-output name=MYVARIABLE::$(sed -n -e '/$string1/ s/.*\= *//p' ./test.test)"
      - name: MYVARIABLE1
        id: MYVARIABLE1
        run: echo "::set-output name=MYVARIABLE::$(sed -n -e '/$string2/ s/.*\= *//p' ./test.test)"
      - name: Output
        run: echo "${{ steps.MYVARIABLE.outputs.MYVARIABLE }} - ${{ steps.MYVARIABLE1.outputs.MYVARIABLE }}"
      - name: Tt
        id: tt
        run: echo "::set-output name=TEST::$(cat ./test.test)"
      - name: aa
        run: echo "${{ steps.tt.outputs.TEST }}"
