name: Test

on:
  push:
    tags:
      - 'Test*'
      - 'Release*'

jobs:
  justEcho:
    runs-on: ubuntu-latest
    steps:
      - name: Just echo Test
        if: startsWith(github.ref, 'refs/tags/Test') 
        run: echo "Hallo Test ${{ github.ref }}"
      - name: Just echo Release
        if: startsWith(github.ref, 'refs/tags/Release') 
        run: echo "Hallo Test ${{ github.ref }}"
      - name: Just echo
        run: echo "Hallo Test ${{ github.ref }}"
