name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      # - run: git show $REVISION:$FILENAME
      - id: test
        run: |
          test1=git branch -a | grep -q 'remotes/origin/gh-pages'
          echo "::set-output name=test::${{test1}}"
      - run: echo "${{steps.test.outputs.test}}"