name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      # - run: git show $REVISION:$FILENAME
      - id: test
        run: |
          echo "::set-output name=npm_version::$(npm view @${{github.repository}} version)"
          echo "::set-output name=ghp::$(git branch -a | grep -q 'remotes/origin/gh-pages')"
      - run: echo "${{steps.test.outputs.npm_version}}"
      - run: echo "${{steps.test.outputs.ghp}}"