name: Version Increment

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      # - run: git show $REVISION:$FILENAME
      - id: test
        run: |
          echo "::set-output name=ghp::$(git branch -a | grep -q 'remotes/origin/gh-pages' && echo $?)"
      - run: echo "${{steps.test.outputs.ghp}}"
      # - run: echo "ACTION_MODE=${{ fromJson(env.TEST_TEST).actionMode }}" >> $GITHUB_ENV
      - name: is gh-pages available
        if: steps.test.outputs.ghp == 0
        run: echo "available"
      - name: is gh-pages not available
        if: steps.test.outputs.ghp != 0
        run: echo "not available"